#!/bin/sh

set -e

lb config noauto \
	--architectures amd64 \
	--debian-installer live \
	--binary-images iso-hybrid \
	--archive-areas "main contrib non-free" \
	--mirror-bootstrap http://mirrors.digitalocean.com/debian/ \
	--bootappend-live "boot=live config keyboard-layouts=ch username=chux hostname=chux user-fullname=chux@chux toram" \
	"${@}"
