#!/bin/sh

set -e

lb config noauto \
	--architectures i386 \
	--debian-installer live \
	-b hdd \
	--archive-areas "main contrib non-free" \
	--bootappend-live "boot=live config locales=de_CH.UTF-8 keyboard-layouts=sg username=chux hostname=chuxhost user-fullname=chux@chuxhost persistence" \
	"${@}"
