# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 0);
user_pref("app.update.lastUpdateTime.datareporting-healthreport-lastDailyCollection", 0);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.frecency_experiment", 2);
user_pref("browser.download.dir", "/home/chux");
user_pref("browser.download.folderList", 0);
user_pref("browser.download.importedFromSqlite", true);
user_pref("browser.migration.version", 36);
user_pref("browser.newtabpage.enhanced", false);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.importBookmarksHTML", false);
user_pref("browser.places.smartBookmarksVersion", 7);
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1469554496439");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1469558096439");
user_pref("browser.search.countryCode", "CH");
user_pref("browser.search.region", "CH");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20160607223741");
user_pref("browser.shell.checkDefaultBrowser", true);
user_pref("browser.shell.mostRecentDateSetAsDefault", "1469554711");
user_pref("browser.slowStartup.averageTime", 1043);
user_pref("browser.slowStartup.samples", 1);
user_pref("browser.startup.homepage_override.buildID", "20160607223741");
user_pref("browser.startup.homepage_override.mstone", "45.2.0");
user_pref("browser.startup.page", 0);
user_pref("browser.syncPromoViewsLeftMap", "{\"addons\":3}");
user_pref("browser.tabs.loadInBackground", false);
user_pref("browser.toolbarbuttons.introduced.pocket-button", true);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"PanelUI-contents\":[\"edit-controls\",\"new-window-button\",\"privatebrowsing-button\",\"save-page-button\",\"print-button\",\"history-panelmenu\",\"fullscreen-button\",\"find-button\",\"preferences-button\",\"add-ons-button\",\"developer-button\"],\"addon-bar\":[\"addonbar-closebutton\",\"status-bar\"],\"PersonalToolbar\":[\"personal-bookmarks\"],\"nav-bar\":[\"urlbar-container\",\"search-container\",\"zoom-controls\",\"bookmarks-menu-button\",\"downloads-button\",\"home-button\",\"loop-button\",\"rpcontinuedToolbarButton\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"toolbar-menubar\":[\"menubar-items\"]},\"seen\":[\"rpcontinuedToolbarButton\",\"loop-button\"],\"dirtyAreaCache\":[\"PersonalToolbar\",\"nav-bar\",\"TabsToolbar\",\"toolbar-menubar\",\"PanelUI-contents\",\"addon-bar\"],\"currentVersion\":5,\"newElementCount\":0}");
user_pref("browser.urlbar.userMadeSearchSuggestionsChoice", true);
user_pref("browser.zoom.siteSpecific", false);
user_pref("datareporting.healthreport.nextDataSubmissionTime", "1469640893114");
user_pref("datareporting.healthreport.service.firstRun", true);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1469554543082");
user_pref("datareporting.policy.firstRunTime", "1469554493114");
user_pref("datareporting.sessions.current.activeTicks", 3);
user_pref("datareporting.sessions.current.clean", true);
user_pref("datareporting.sessions.current.firstPaint", 1100);
user_pref("datareporting.sessions.current.main", 10);
user_pref("datareporting.sessions.current.sessionRestored", 1063);
user_pref("datareporting.sessions.current.startTime", "1469554710512");
user_pref("datareporting.sessions.current.totalTime", 15);
user_pref("datareporting.sessions.currentIndex", 3);
user_pref("datareporting.sessions.previous.0", "{\"s\":1469554491712,\"a\":7,\"t\":37,\"c\":true,\"m\":11,\"fp\":548,\"sr\":2042}");
user_pref("datareporting.sessions.previous.1", "{\"s\":1469554531995,\"a\":3,\"t\":12,\"c\":true,\"m\":20,\"fp\":1009,\"sr\":1094}");
user_pref("datareporting.sessions.previous.2", "{\"s\":1469554693853,\"a\":3,\"t\":14,\"c\":true,\"m\":10,\"fp\":1024,\"sr\":1108}");
user_pref("dom.apps.reset-permissions", true);
user_pref("dom.mozApps.used", true);
user_pref("experiments.activeExperiment", false);
user_pref("extensions.blocklist.pingCountVersion", -1);
user_pref("extensions.bootstrappedAddons", "{\"loop@mozilla.org\":{\"version\":\"1.1.14\",\"type\":\"extension\",\"descriptor\":\"/usr/lib/firefox-esr/browser/features/loop@mozilla.org.xpi\",\"multiprocessCompatible\":false,\"runInSafeMode\":true}}");
user_pref("extensions.databaseSchema", 17);
user_pref("extensions.e10sBlockedByAddons", true);
user_pref("extensions.enabledAddons", "nosquint%40urandom.ca:2.1.9,%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:45.2.0");
user_pref("extensions.getAddons.cache.lastUpdate", 1469554493);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.lastAppVersion", "45.2.0");
user_pref("extensions.lastPlatformVersion", "45.2.0");
user_pref("extensions.nosquint.prefsVersion", "2.0");
user_pref("extensions.nosquint.version", "2.1.9");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.requestpolicy.lastAppVersion", "38.2.1");
user_pref("extensions.requestpolicy.lastVersion", "1.0.beta11pre4.1452.r38c6478");
user_pref("extensions.requestpolicy.welcomeWindowShown", true);
user_pref("extensions.shownSelectionUI", true);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.ui.dictionary.hidden", true);
user_pref("extensions.ui.experiment.hidden", true);
user_pref("extensions.ui.lastCategory", "addons://list/extension");
user_pref("extensions.ui.locale.hidden", true);
user_pref("extensions.xpiState", "{\"app-profile\":{\"rpcontinued@non-amo.requestpolicy.org\":{\"d\":\"/home/chux/.mozilla/firefox/r7cztrxw.default/extensions/rpcontinued@non-amo.requestpolicy.org.xpi\",\"e\":false,\"v\":\"1.0.beta11pre4.1452.r38c6478\",\"st\":1469473374000}},\"app-system-defaults\":{\"loop@mozilla.org\":{\"d\":\"/usr/lib/firefox-esr/browser/features/loop@mozilla.org.xpi\",\"e\":true,\"v\":\"1.1.14\",\"st\":1465342526000}},\"app-global\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"d\":\"/usr/lib/firefox-esr/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}.xpi\",\"e\":true,\"v\":\"45.2.0\",\"st\":1465342525000}},\"app-system-share\":{\"nosquint@urandom.ca\":{\"d\":\"/usr/share/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/nosquint@urandom.ca\",\"e\":true,\"v\":\"2.1.9\",\"st\":1469132866000,\"mt\":1366480324000}}}");
user_pref("gecko.buildID", "20160607223741");
user_pref("gecko.mstone", "45.2.0");
user_pref("media.gmp-manager.buildID", "20150828090403");
user_pref("mousewheel.withcontrolkey.action", 3);
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.dns.disablePrefetch", true);
user_pref("network.http.speculative-parallel-limit", 0);
user_pref("network.prefetch-next", false);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.history.expiration.transient_current_max_pages", 65821);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("plugin.importedState", true);
user_pref("pref.general.disable_button.default_browser", false);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.startup.last_success", 1469554710);
user_pref("toolkit.telemetry.cachedClientID", "68694a10-800f-4dee-bab7-58ab670f550b");
user_pref("toolkit.telemetry.previousBuildID", "20160607223741");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
