# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 0);
user_pref("browser.cache.disk.capacity", 266240);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.frecency_experiment", 2);
user_pref("browser.download.dir", "/home/chux");
user_pref("browser.download.folderList", 0);
user_pref("browser.download.importedFromSqlite", true);
user_pref("browser.migration.version", 27);
user_pref("browser.newtabpage.enhanced", false);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.importBookmarksHTML", false);
user_pref("browser.places.smartBookmarksVersion", 7);
user_pref("browser.search.countryCode", "CH");
user_pref("browser.search.region", "CH");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20150828090403");
user_pref("browser.shell.checkDefaultBrowser", true);
user_pref("browser.slowStartup.averageTime", 1071);
user_pref("browser.slowStartup.samples", 3);
user_pref("browser.startup.page", 0);
user_pref("browser.syncPromoViewsLeftMap", "{\"addons\":3}");
user_pref("browser.tabs.loadInBackground", false);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"PanelUI-contents\":[\"edit-controls\",\"new-window-button\",\"privatebrowsing-button\",\"save-page-button\",\"print-button\",\"history-panelmenu\",\"fullscreen-button\",\"find-button\",\"preferences-button\",\"add-ons-button\",\"developer-button\"],\"addon-bar\":[\"addonbar-closebutton\",\"status-bar\"],\"PersonalToolbar\":[\"personal-bookmarks\"],\"nav-bar\":[\"urlbar-container\",\"search-container\",\"zoom-controls\",\"bookmarks-menu-button\",\"downloads-button\",\"home-button\",\"loop-button\",\"rpcontinuedToolbarButton\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"toolbar-menubar\":[\"menubar-items\"]},\"seen\":[\"rpcontinuedToolbarButton\"],\"dirtyAreaCache\":[\"PersonalToolbar\",\"nav-bar\",\"TabsToolbar\",\"toolbar-menubar\",\"PanelUI-contents\",\"addon-bar\"],\"currentVersion\":4,\"newElementCount\":0}");
user_pref("browser.zoom.siteSpecific", false);
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.bootstrappedAddons", "{\"rpcontinued@non-amo.requestpolicy.org\":{\"version\":\"1.0.beta11pre4.1452.r38c6478\",\"type\":\"extension\",\"descriptor\":\"/home/chux/.mozilla/firefox/r7cztrxw.default/extensions/rpcontinued@non-amo.requestpolicy.org.xpi\",\"multiprocessCompatible\":false}}");
user_pref("extensions.databaseSchema", 16);
user_pref("extensions.enabledAddons", "nosquint%40urandom.ca:2.1.9,%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:38.2.1");
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.lastAppVersion", "38.2.1");
user_pref("extensions.lastPlatformVersion", "38.2.1");
user_pref("extensions.nosquint.prefsVersion", "2.0");
user_pref("extensions.nosquint.version", "2.1.9");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.requestpolicy.lastAppVersion", "38.2.1");
user_pref("extensions.requestpolicy.lastVersion", "1.0.beta11pre4.1452.r38c6478");
user_pref("extensions.requestpolicy.welcomeWindowShown", true);
user_pref("extensions.shownSelectionUI", true);
user_pref("extensions.ui.dictionary.hidden", true);
user_pref("extensions.ui.experiment.hidden", true);
user_pref("extensions.ui.lastCategory", "addons://list/extension");
user_pref("extensions.ui.locale.hidden", true);
user_pref("extensions.xpiState", "{\"app-global\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"d\":\"/usr/lib/iceweasel/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"e\":true,\"v\":\"38.2.1\",\"st\":1456525729000,\"mt\":1440757518000}},\"app-system-share\":{\"nosquint@urandom.ca\":{\"d\":\"/usr/share/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/nosquint@urandom.ca\",\"e\":true,\"v\":\"2.1.9\",\"st\":1456525775000,\"mt\":1366480324000}},\"app-profile\":{\"rpcontinued@non-amo.requestpolicy.org\":{\"d\":\"/home/chux/.mozilla/firefox/r7cztrxw.default/extensions/rpcontinued@non-amo.requestpolicy.org.xpi\",\"e\":true,\"v\":\"1.0.beta11pre4.1452.r38c6478\",\"st\":1456609180000}}}");
user_pref("gecko.buildID", "20150828090403");
user_pref("gecko.mstone", "38.2.1");
user_pref("media.gmp-manager.buildID", "20150828090403");
user_pref("mousewheel.withcontrolkey.action", 3);
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.dns.disablePrefetch", true);
user_pref("network.http.speculative-parallel-limit", 0);
user_pref("network.prefetch-next", false);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.history.expiration.transient_current_max_pages", 24545);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("pref.general.disable_button.default_browser", false);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.startup.last_success", 1456609855);
user_pref("toolkit.telemetry.previousBuildID", "20150828090403");
